[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "Password Keyword Match"
Description = "Detect password keyword in file content"
MatchAction = "Snaffle"
MatchLocation = "FileContentAsString"
WordListType = "Regex"
WordList = [
    "ftp://",
]
CaseSensitive = false
Triage = "Red"
