[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "Internal IP Keyword Match"
Description = "Detect password keyword in file content"
MatchAction = "Snaffle"
MatchLocation = "FileContentAsString"
WordListType = "Regex"
WordList = [
    "@10\\.110",
]
CaseSensitive = false
Triage = "Red"
