[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "U Keyword Match"
Description = "Detect password keyword in file content"
MatchAction = "Snaffle"
MatchLocation = "FileContentAsString"
WordListType = "Regex"
WordList = [
    "-U",
]
CaseSensitive = false
Triage = "Red"
