[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "User Slash Keyword Match"
Description = "Detect password keyword in file content"
MatchAction = "Snaffle"
MatchLocation = "FileContentAsString"
WordListType = "Regex"
WordList = [
    "/user",
]
CaseSensitive = false
Triage = "Red"
