[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "Username Keyword Match"
Description = "Detect password keyword in file content"
MatchAction = "Snaffle"
MatchLocation = "FileContentAsString"
WordListType = "Regex"
WordList = [
    "--username",
]
CaseSensitive = false
Triage = "Red"
